### ISSUE TITLE
The API https://iptv-org.github.io/api/channels.json does not have the streaming url, the ideal would be to have a single Json with all the information

### ISSUE THREAD

**Issue by Buhos-Dev** [iptv-org/api#17] opened 2023-05-23 03:15 UTC
The API https://iptv-org.github.io/api/channels.json does not have the streaming url, the ideal would be to have a single Json with all the information

_Originally posted by @Buhos-Dev in https://github.com/iptv-org/api/issues/16#issuecomment-1558448792_

**Comment by freearhey** [comment] 2023-05-23 15:10
Duplicate of #16

**Closed by freearhey** 2023-05-23 15:10 UTC
